### ISSUE TITLE
Add to bower and pursuit?

### ISSUE THREAD

**Issue by sharkdp** [hdgarrood/purescript-orders#1]
I only found this library by chance through Github search.

Is there anything keeping you from adding this to the bower registry (+ upload to Pursuit)?

Personally, I would like to see the generalized functions for `min` and `max` in the Prelude (like in your PR here https://github.com/purescript/purescript-prelude/pull/27). But if this is not going to happen, this library is very useful.

**Comment by hdgarrood** [comment]
Yes - the main thing keeping me from adding this to Bower and Pursuit is time. I don't have very much to spare during semesters. There's also the problem that I wrote this back when it looked like Prelude was going to have partial orderings and lattices and this stuff, so someone would need to go over it all and check that it still makes sense based on what's currently in Prelude. My guess is that a lot of it doesn't.

**Comment by hdgarrood** [comment]
Done! http://pursuit.purescript.org/packages/purescript-orders/0.1.0 /cc @tfausak

**Comment by tfausak** [comment]
:+1: Thank you!

**Comment by sharkdp** [comment]
Thanks!
