### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by paf31** [hdgarrood/purescript-orders#2]
Could you please add a LICENSE so I can use this for other projects?

**Comment by hdgarrood** [comment]
Ah of course, will do.

**Comment by hdgarrood** [comment]
I think you and @joneshf probably ought to be on there too, since much of this was lifted directly from that issue in prelude. Shall I just list the three of us in the LICENSE file?

**Comment by paf31** [comment]
I'm happy to assign ownership of any parts I may have written to you :smile:

**Comment by hdgarrood** [comment]
Ok then. Come to think of it, how would you feel about moving this repo under the purescript org?

**Comment by paf31** [comment]
Sounds good to me. We'd just need to add `travis.yml` and the other usual bits.

**Comment by hdgarrood** [comment]
Ok, how does it look now? I copied them from prelude, but I left out the FFI stuff, since this package doesn't use it (and I expect it will stay that way). Also I updated .travis.yml to test on some later node versions.

**Comment by joneshf** [comment]
> I'm happy to assign ownership of any parts I may have written to you

ditto

**Comment by paf31** [comment]
I think this looks good. @garyb, is there anything else we would usually set up in a core library?

**Comment by garyb** [comment]
Nope, I think this has all the important stuff :+1: 

Could add badges in the README perhaps, but we can do that whenever.

**Comment by hdgarrood** [comment]
Cool. Github won't let me transfer because I don't have admin rights but maybe you could just create a repo on github and push this one to it.

**Comment by paf31** [comment]
You should have admin access [here](https://github.com/purescript/purescript-orders) now. Thanks!
